import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    image: "",
    title: "Lenevo Ideapad 3",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "50000",
    discount: "10",
    brand: "Lenevo",
    category: "laptop",
    inStock: true,
    fastDelivery: false,
    ratings: 3.5,
    itemInStock: 1,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Acer Aspire 7",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "49000",
    discount: "33",
    brand: "Acer",
    category: "laptop",
    inStock: true,
    fastDelivery: false,
    ratings: 4.5,
    itemInStock: 1,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Oppo Reno 7",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "37999",
    discount: "30",
    brand: "oppo",
    category: "Mobile",
    inStock: true,
    fastDelivery: false,
    ratings: 3.8,
    itemInStock: 1,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Honor 9n",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "9599",
    discount: "20",
    brand: "Honor",
    category: "Mobile",
    inStock: false,
    fastDelivery: false,
    ratings: 3.2,
    itemInStock: 1,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "HP Pavillion Gaming",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "59000",
    discount: "5",
    brand: "HP",
    category: "laptop",
    inStock: true,
    fastDelivery: true,
    ratings: 4.6,
    itemInStock: 1,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Acer Nitro 5",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "75999",
    discount: "20",
    brand: "Acer",
    category: "Laptop",
    inStock: false,
    fastDelivery: true,
    ratings: 4.8,
    itemInStock: 1,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Galaxy Tab A8",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "19999",
    discount: "30",
    brand: "Galaxy",
    category: "Tablet",
    inStock: false,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 1,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Realme PAD 4",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "17700",
    discount: "40",
    brand: "Realme",
    category: "Tablet",
    inStock: true,
    fastDelivery: true,
    ratings: 4.2,
    itemInStock: 1,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Dell Inspiration 15",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "67000",
    discount: "35",
    brand: "Dell",
    category: "Laptop",
    inStock: false,
    fastDelivery: false,
    ratings: 4.6,
    itemInStock: 1,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
  {
    _id: uuid(),
    image: "",
    title: "Redmi NOTE 11",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit Necessitatibus, est!",
    price: "18990",
    discount: "30",
    brand: "Redmi",
    category: "Monile",
    inStock: true,
    fastDelivery: false,
    ratings: 4,
    itemInStock: 4,
    quantity: 1,
    color: "black",
    idealFor: ["Men", "Women", "Girl", "Boy", "Senior"],
    level: ["beginner", "amateur", "intermediate", "advanced", "professional"],
    offer: ["Save 50", "70% bonanza", "Republic Day Sale"],
  },
];
